import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="text-xl bg-slate-800 text-white">
      <body className={montserrat.className}>
        <main className="min-h-screen mx-auto p-4 max-w-xl">{children}</main>
      </body>
    </html>
  );
}
